/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controllers.Serialize;
import Entities.Routes;
import Entities.User;
import EntitySets.SetOfRoutes;
import EntitySets.SetOfUsers;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.jdesktop.xswingx.PromptSupport;

/**
 *
 * @author CRYSIS_POOL
 */
public class AddRoutes extends javax.swing.JFrame {

    /**
     * Creates new form AddRoutes
     */
    public AddRoutes() {
        initComponents();
        
        PromptSupport.setPrompt("Enter Vehical No", txtVehicalNo);
        PromptSupport.setPrompt("Enter no of stops", txtNoOfStops);
        PromptSupport.setPrompt("Enter driver ID", txtDriverID);
        PromptSupport.setPrompt("Enter inspector ID", txtInspectorID);       
        
        PromptSupport.setFocusBehavior(PromptSupport.FocusBehavior.SHOW_PROMPT, txtVehicalNo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        cbFrom = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        cbTo = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txtVehicalNo = new javax.swing.JTextField();
        txtDriverID = new javax.swing.JTextField();
        txtNoOfStops = new javax.swing.JTextField();
        dcDate = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        btnBack1 = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        txtInspectorID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(250, 400));
        setMinimumSize(new java.awt.Dimension(250, 400));
        setPreferredSize(new java.awt.Dimension(250, 400));
        setResizable(false);
        setSize(new java.awt.Dimension(250, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel2.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        btnLogout.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, -1, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 40));

        cbFrom.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        cbFrom.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 150, -1));

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        jLabel1.setText("Date");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        cbTo.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        cbTo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 150, -1));

        jLabel2.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        jLabel2.setText("From");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        txtVehicalNo.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        getContentPane().add(txtVehicalNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 210, -1));

        txtDriverID.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        getContentPane().add(txtDriverID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 210, -1));

        txtNoOfStops.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        getContentPane().add(txtNoOfStops, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 210, -1));
        getContentPane().add(dcDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 170, -1));

        jLabel3.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        jLabel3.setText("To");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        btnBack1.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        btnBack1.setText("Back");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        btnSubmit.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, -1, 40));

        txtInspectorID.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        getContentPane().add(txtInspectorID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 210, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        AdminHome ah = new AdminHome();
        ah.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        Login lg = new Login();
        lg.setVisible(true);

        lg.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBack1ActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed

        String from = cbFrom.getSelectedItem().toString();
        String to = cbTo.getSelectedItem().toString();
        String vehicalNo = txtVehicalNo.getText();
        String noOfStops = txtNoOfStops.getText();
        String driverID = txtDriverID.getText();
        String inspectorID = txtInspectorID.getText();
        String date = dcDate.getDate().toString();
        
        SetOfRoutes<Routes> sOr;
        
        try{
            sOr= (SetOfRoutes)Serialize.deserialize("SetOfRoutes.ser");
        }catch(IOException | ClassNotFoundException e)
        {
            sOr = new SetOfRoutes();
        }
        
        SetOfUsers<User> sOu;
        try{
            sOu = (SetOfUsers)Serialize.deserialize("SetOfUsers.ser");
        }catch(Exception e){
            return;
        }
        
        int dConfo = 0, iConfo=0;
        
        for(User temp:sOu)
        {
            if(driverID.equals(temp.getUserID()))
            {
                dConfo = 1; 
            }                
        }
        
        for(User temp2:sOu)
        {
            if(inspectorID.equals(temp2.getUserID()))
            {
                iConfo = 1;
            }
        }
        
        if(dConfo==1 && iConfo==1)
        {
            sOr.add(new Routes(from, to, vehicalNo, noOfStops, driverID, inspectorID, date));
            try {
                Serialize.serialize(sOr,"SetOfRoutes.ser");
                JOptionPane.showMessageDialog(rootPane, "Route added successfully");
            } catch (IOException ex) {
                Logger.getLogger(Routes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
            JOptionPane.showMessageDialog(rootPane, "Check driver ID and inspector ID");
  
        for(Routes temp:sOr)
        {
            String tempFrom = temp.getFrom();
            String tempTo = temp.getTo();
            String tempVehicalNo = temp.getVehicalNo();
            System.out.println(""+tempFrom+","+tempTo+","+tempVehicalNo);
        }
        
    }//GEN-LAST:event_btnSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddRoutes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddRoutes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddRoutes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddRoutes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddRoutes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox cbFrom;
    private javax.swing.JComboBox cbTo;
    private com.toedter.calendar.JDateChooser dcDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtDriverID;
    private javax.swing.JTextField txtInspectorID;
    private javax.swing.JTextField txtNoOfStops;
    private javax.swing.JTextField txtVehicalNo;
    // End of variables declaration//GEN-END:variables
}
