/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controllers.Serialize;
import Entities.vehicle;
import EntitySets.SetOfVehicles;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.jdesktop.xswingx.PromptSupport;

/**
 *
 * @author CRYSIS_POOL
 */
public class AddVehical extends javax.swing.JFrame {

    /**
     * Creates new form AddVehical
     */
    public AddVehical() {
        initComponents();
        //PromptSupport.setPrompt("Enter Vehical ID", txtVehicalID);
        PromptSupport.setPrompt("Enter Vehical No", txtVehicalNo);
        PromptSupport.setPrompt("Enter Vehical Model", txtVehicalModel);
        
        
        //PromptSupport.setFocusBehavior(PromptSupport.FocusBehavior.SHOW_PROMPT, txtVehicalID);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnvehicle = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        txtVehicalModel = new javax.swing.JTextField();
        txtVehicalNo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        dcDate = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        rbBus = new javax.swing.JRadioButton();
        rbTrain = new javax.swing.JRadioButton();
        rbTram = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(250, 400));
        setMinimumSize(new java.awt.Dimension(250, 400));
        setPreferredSize(new java.awt.Dimension(250, 400));
        setResizable(false);
        setSize(new java.awt.Dimension(250, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.setMaximumSize(new java.awt.Dimension(80, 30));
        btnBack.setMinimumSize(new java.awt.Dimension(80, 30));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel2.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 30));

        btnLogout.setBackground(new java.awt.Color(255, 255, 255));
        btnLogout.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.setMaximumSize(new java.awt.Dimension(80, 30));
        btnLogout.setMinimumSize(new java.awt.Dimension(80, 30));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 80, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 40));

        txtVehicalModel.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        getContentPane().add(txtVehicalModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 180, 20));

        txtVehicalNo.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        getContentPane().add(txtVehicalNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 180, 20));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Date");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        btnSubmit.setBackground(new java.awt.Color(255, 255, 255));
        btnSubmit.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnSubmit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSubmit.setMaximumSize(new java.awt.Dimension(80, 30));
        btnSubmit.setMinimumSize(new java.awt.Dimension(80, 30));
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 80, 30));
        getContentPane().add(dcDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 130, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Vehicle");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        btnvehicle.add(rbBus);
        rbBus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbBus.setText("Bus");
        getContentPane().add(rbBus, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        btnvehicle.add(rbTrain);
        rbTrain.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbTrain.setText("Train");
        getContentPane().add(rbTrain, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        btnvehicle.add(rbTram);
        rbTram.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbTram.setText("Tram");
        getContentPane().add(rbTram, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        Login lg = new Login();
        lg.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        VehicalDetails vd = new VehicalDetails();
        vd.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        String vehicleName="";
        if(rbBus.isSelected())
                vehicleName="Bus";
        else if(rbTrain.isSelected())
                vehicleName="Train";
        else if(rbTram.isSelected())
                vehicleName="Tram";
        String vehiNo=txtVehicalNo.getText();
        String vehiModel=txtVehicalModel.getText();
        Date date=dcDate.getDate();
        DateFormat df = new SimpleDateFormat("MM/dd/yyyy");
        String str=df.format(date);
        System.out.println(str);
        
        int type=7;
        if(rbBus.isSelected())
                type=1;
        else if(rbTrain.isSelected())
                type=2;
        else if(rbTram.isSelected())
                type=3;
        
        
        String err="";
        int errcheck=0;
        
        if(!(rbBus.isSelected()||rbTrain.isSelected()||rbTram.isSelected()))
        {
            err+="\n Must Select a type";
            errcheck=1;
        }
        if(vehiNo.isEmpty())
        {
            err+="\n Must Enter an VehicleNumber";
            errcheck=1;
        }
        if(vehiModel.isEmpty())
        {
            err+="\n Must Enter an VehicleModel";
            errcheck=1;
        }
        
        if(str.isEmpty()) 
        {
            err+="\n Must Enter an Date";
            errcheck=1;
        }
        
        if(errcheck==1)
        {
            JOptionPane.showMessageDialog(rootPane, err);
            return;
        }
        
        else {
            
            
            SetOfVehicles<vehicle> sOv;
        try{
            sOv = (SetOfVehicles)Serialize.deserialize("SetOfVehicles.ser");
        }catch(IOException | ClassNotFoundException e)
        {
            sOv = new SetOfVehicles<>();
        }
        int buscount=1;
        int trncount=1;
        int trmcount=1;
        
        for(vehicle ve:sOv)
        {
            if(ve.getType().equalsIgnoreCase("bus"))
            {
                buscount++;
                vehicle.setBusCount(buscount);
            }
            if(ve.getType().equalsIgnoreCase("train"))
            {
                trncount++;
                vehicle.setTrainCount(trncount);
            }
            if(ve.getType().equalsIgnoreCase("tram"))
            {
                trmcount++;
                vehicle.setTramCount(trmcount);
            }
            
            
            if(vehiNo.equals(ve.getVehiNo())){
                JOptionPane.showMessageDialog(rootPane, "Vehicle already exists.");
                return;
            }
            
        }
        
        
        sOv.add(new vehicle(vehicleName, vehiNo, vehiModel, str, type));
        
            try {
                Serialize.serialize(sOv,"SetOfVehicles.ser");
            } catch (IOException ex) {
                Logger.getLogger(Signup.class.getName()).log(Level.SEVERE, null, ex);
            }
           
        for(vehicle sOv1:sOv)
        {
            String id=sOv1.getVehiID();
            String ve=sOv1.getVehicleName();
            String velno=sOv1.getVehiNo();
            String velmo=sOv1.getVehiModel();
            String d=sOv1.getDate();
                
            System.out.println(""+id+","+ve+","+velno+","+velmo+","+d+"");
        }
         
        //new Login().setVisible(true);
        //this.dispose();
            
        }
        
    }//GEN-LAST:event_btnSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddVehical.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddVehical.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddVehical.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddVehical.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddVehical().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSubmit;
    private javax.swing.ButtonGroup btnvehicle;
    private com.toedter.calendar.JDateChooser dcDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton rbBus;
    private javax.swing.JRadioButton rbTrain;
    private javax.swing.JRadioButton rbTram;
    private javax.swing.JTextField txtVehicalModel;
    private javax.swing.JTextField txtVehicalNo;
    // End of variables declaration//GEN-END:variables
}
