/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controllers.Serialize;
import Controllers.Session;
import static Controllers.Session.currentUser;
import Entities.User;
import EntitySets.SetOfUsers;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Kaashiff Ahamed
 */
public class PassangerProfile extends javax.swing.JFrame {

    /**
     * Creates new form PassangerProfile
     */
    SetOfUsers<User> sOu;
    public PassangerProfile() {
        initComponents();
        lblName.setText(currentUser.getUserFulName());
        lblUserName.setText(currentUser.getUserName());
        lblEmail.setText(currentUser.geteMail());
        lblAddress.setText(currentUser.getAddress());
        lblPhone.setText(currentUser.getMobileNumber());
        lblGender.setText(currentUser.getGender());
        lblBalance.setText(Float.toString(currentUser.getBalance()));
        lblLoan.setText(Boolean.toString(currentUser.isLoanStatus()));
          
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        btnUpdateDetails = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblBalance = new javax.swing.JLabel();
        btnTopup = new javax.swing.JButton();
        lblLoan = new javax.swing.JLabel();
        btnLoan = new javax.swing.JButton();
        label1 = new javax.swing.JLabel();
        lable2 = new javax.swing.JLabel();
        btnCardDetails = new javax.swing.JButton();
        label3 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        label6 = new javax.swing.JLabel();
        label7 = new javax.swing.JLabel();
        label8 = new javax.swing.JLabel();
        lable3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(250, 400));
        setMinimumSize(new java.awt.Dimension(250, 400));
        setPreferredSize(new java.awt.Dimension(250, 400));
        setResizable(false);
        setSize(new java.awt.Dimension(250, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblName.setText("Name");
        getContentPane().add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 120, -1));

        lblUserName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblUserName.setText("username");
        getContentPane().add(lblUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 120, -1));

        lblEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblEmail.setText("email");
        getContentPane().add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 120, -1));

        lblAddress.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblAddress.setText("address");
        getContentPane().add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 120, -1));

        lblPhone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblPhone.setText("phone");
        getContentPane().add(lblPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 120, -1));

        lblGender.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblGender.setText("gender");
        getContentPane().add(lblGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 120, -1));

        btnUpdateDetails.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdateDetails.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        btnUpdateDetails.setText("Update Details");
        btnUpdateDetails.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnUpdateDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdateDetails.setMaximumSize(new java.awt.Dimension(80, 30));
        btnUpdateDetails.setMinimumSize(new java.awt.Dimension(80, 30));
        getContentPane().add(btnUpdateDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 100, 30));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Account "));
        jPanel1.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBalance.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblBalance.setText("balnce");
        jPanel1.add(lblBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        btnTopup.setBackground(new java.awt.Color(255, 255, 255));
        btnTopup.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        btnTopup.setText("Top Up");
        btnTopup.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnTopup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTopup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTopupActionPerformed(evt);
            }
        });
        jPanel1.add(btnTopup, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 90, -1));

        lblLoan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblLoan.setText("loan");
        jPanel1.add(lblLoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        btnLoan.setBackground(new java.awt.Color(255, 255, 255));
        btnLoan.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        btnLoan.setText("Get Loan");
        btnLoan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnLoan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoanActionPerformed(evt);
            }
        });
        jPanel1.add(btnLoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 90, -1));

        label1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label1.setText("Balance: ");
        jPanel1.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        lable2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lable2.setText("Loan:");
        jPanel1.add(lable2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 220, 60));

        btnCardDetails.setBackground(new java.awt.Color(255, 255, 255));
        btnCardDetails.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        btnCardDetails.setText("card");
        btnCardDetails.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnCardDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCardDetails.setMaximumSize(new java.awt.Dimension(80, 30));
        btnCardDetails.setMinimumSize(new java.awt.Dimension(80, 30));
        btnCardDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCardDetailsActionPerformed(evt);
            }
        });
        getContentPane().add(btnCardDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 80, 30));

        label3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label3.setText("Name");
        getContentPane().add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 40, -1));

        label4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label4.setText("Username");
        getContentPane().add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        label5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label5.setText("Email ID");
        getContentPane().add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        label6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label6.setText("Address");
        getContentPane().add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        label7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label7.setText("Contact No");
        getContentPane().add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        label8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label8.setText("Gender");
        getContentPane().add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        lable3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lable3.setText("Add card details");
        getContentPane().add(lable3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 150, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.setMaximumSize(new java.awt.Dimension(80, 30));
        btnBack.setMinimumSize(new java.awt.Dimension(80, 30));
        jPanel2.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 30));

        btnLogout.setBackground(new java.awt.Color(255, 255, 255));
        btnLogout.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.setMaximumSize(new java.awt.Dimension(80, 30));
        btnLogout.setMinimumSize(new java.awt.Dimension(80, 30));
        jPanel2.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 80, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoanActionPerformed
      
        try {
            sOu=(SetOfUsers<User>) Serialize.deserialize("SetOfUsers.ser");
        } catch (IOException ex) {
            Logger.getLogger(PassangerProfile.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PassangerProfile.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        sOu.updateBalance(sOu,currentUser.getUserName(),currentUser.getLoanAmount());
        
        try {
            Serialize.serialize(sOu,"SetOfUsers.ser");
        } catch (IOException ex) {
            Logger.getLogger(PassangerProfile.class.getName()).log(Level.SEVERE, null, ex);
        }
        lblBalance.setText(Float.toString(currentUser.getBalance()));
        lblLoan.setText(Boolean.toString(currentUser.isLoanStatus()));
      
    }//GEN-LAST:event_btnLoanActionPerformed

    private void btnTopupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTopupActionPerformed
        AddAmount aa = new AddAmount();
        aa.setVisible(true);
        
    }//GEN-LAST:event_btnTopupActionPerformed

    private void btnCardDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCardDetailsActionPerformed
        ViewCardDetails vcd = new ViewCardDetails();
        vcd.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnCardDetailsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PassangerProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PassangerProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PassangerProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PassangerProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PassangerProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCardDetails;
    private javax.swing.JButton btnLoan;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnTopup;
    private javax.swing.JButton btnUpdateDetails;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel label8;
    private javax.swing.JLabel lable2;
    private javax.swing.JLabel lable3;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblLoan;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblUserName;
    // End of variables declaration//GEN-END:variables
}
