/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controllers.Serialize;
import Entities.vehicle;
import EntitySets.SetOfVehicles;
import java.io.IOException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CRYSIS_POOL
 */
public class VehicalDetails extends javax.swing.JFrame {

    /**
     * Creates new form VehicalDetails
     */
    SetOfVehicles<vehicle> sOv;
    public VehicalDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnvehiDetails = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblvehiDetails = new javax.swing.JTable();
        btnVehical = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        rbBus = new javax.swing.JRadioButton();
        rbTrain = new javax.swing.JRadioButton();
        rbTram = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(250, 400));
        setMinimumSize(new java.awt.Dimension(250, 400));
        setPreferredSize(new java.awt.Dimension(250, 400));
        setResizable(false);
        setSize(new java.awt.Dimension(250, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel2.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        btnLogout.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, -1, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 40));

        tblvehiDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblvehiDetails);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 220, 130));

        btnVehical.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        btnVehical.setText("Add Vehical");
        btnVehical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehicalActionPerformed(evt);
            }
        });
        getContentPane().add(btnVehical, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, 30));

        txtSearch.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 130, -1));

        btnSearch.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        btnvehiDetails.add(rbBus);
        rbBus.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        rbBus.setText("Bus");
        getContentPane().add(rbBus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        btnvehiDetails.add(rbTrain);
        rbTrain.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        rbTrain.setText("Train");
        getContentPane().add(rbTrain, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        btnvehiDetails.add(rbTram);
        rbTram.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        rbTram.setText("Tram");
        getContentPane().add(rbTram, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        Login lg = new Login();
        lg.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        AdminHome ah = new AdminHome();
        ah.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnVehicalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehicalActionPerformed
        AddVehical ad = new AddVehical();
        ad.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnVehicalActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        searchVehicleByID(tblvehiDetails, sOv, txtSearch, rbBus,rbTrain,rbTram);
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VehicalDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VehicalDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VehicalDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VehicalDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VehicalDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnVehical;
    private javax.swing.ButtonGroup btnvehiDetails;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbBus;
    private javax.swing.JRadioButton rbTrain;
    private javax.swing.JRadioButton rbTram;
    private javax.swing.JTable tblvehiDetails;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

private void searchVehicleByID(JTable tblvehiDetails, SetOfVehicles<vehicle> sOv,JTextField txt,JRadioButton rbbus,JRadioButton rbtrain,JRadioButton rbtram) {
       DefaultTableModel dtm=(DefaultTableModel) tblvehiDetails.getModel();
        dtm.setRowCount(0);
        String text=txt.getText();
        String type="";
        if(rbbus.isSelected())
            type="bus";
        if(rbtrain.isSelected())
            type="train";
        if(rbtram.isSelected())
            type="tram";
        
      try {
          sOv=(SetOfVehicles<vehicle>) Serialize.deserialize("SetOfVehicles.ser");
          
          for(vehicle vel:sOv){
              if(type.equals("")){
                  if(vel.getVehiID().contains(text)){
                  Vector v=new Vector();
                  v.add(vel.getVehiID());
                  v.add(vel.getVehiNo());
                  v.add(vel.getVehiModel());
                  v.add(vel.getDate());
                  Vector h=new Vector();
                  h.add("ID");
                  h.add("VehicleNo");
                  h.add("VehicleModel");
                  h.add("Added Date");
                  dtm.addRow(v);
                  dtm.setColumnIdentifiers(h);
              }
                  
              }
              else{
              if(vel.getVehiID().contains(text) && vel.getType().equals(type)){
                  Vector v=new Vector();
                  v.add(vel.getVehiID());
                  v.add(vel.getVehiNo());
                  v.add(vel.getVehiModel());
                  v.add(vel.getDate());
                  Vector h=new Vector();
                  h.add("ID");
                  h.add("VehicleNo");
                  h.add("VehicleModel");
                  h.add("Added Date");
                  dtm.addRow(v);
                  dtm.setColumnIdentifiers(h);
              }
              }
               tblvehiDetails.setModel(dtm);
               
          }
      } catch (IOException ex) {
          Logger.getLogger(StaffDetails.class.getName()).log(Level.SEVERE, null, ex);
      } catch (ClassNotFoundException ex) {
          Logger.getLogger(StaffDetails.class.getName()).log(Level.SEVERE, null, ex);
      }
    }

}

